const { config } = require('dotenv');
config({ path: `.env.${process.env.NODE_ENV || 'production'}` });

config();

const { NODE_ENV, PORT, DATABASE, DATABASEUSERNAME, DATABASEUSERNAMEPASSWORD, DATABASEHOST, APIHOSTNAME, CRYPTOJSKEY, JWT_EXPIRES_AT, JWT_SECRET_KEY } =
  process.env;
module.exports = {
  NODE_ENV,
  PORT,
  DATABASE,
  DATABASEUSERNAME,
  DATABASEUSERNAMEPASSWORD,
  DATABASEHOST,
  APIHOSTNAME,
  CRYPTOJSKEY,
  JWT_EXPIRES_AT,
  JWT_SECRET_KEY,
};
